# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: This blog is under develpment
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is AgileSight's Kusto develper blog, which is still under construction. 
  When finished it will contain posts and reusable assets that should be very useful when developing applications communicating with Kusto clusters.
  Query / Ingestion.
baseurl: "/kusto-developer-blog" # the subpath of your site, e.g. /blog
url: "https://agilesight.github.io" # the base hostname & protocol for your site
twitter_username: Taffyer 
github_username:  wild-flame 

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
disqus_shortname: kustoblog

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
